DROP TABLE IF EXISTS TB_HEROIS

CREATE TABLE TB_HEROIS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY NOT NULL,
    NOME TEXT NOT NULL,
    PODER TEXT NOT NULL
)

-- CREATE
INSERT INTO TB_HEROIS (NOME, PODER)
VALUES 
    ('Batman', 'Preparo'),
    ('Adão Negro', 'Deus'),
    ('Ciborgue', 'Meio Robô')

-- READ
SELECT * FROM TB_HEROIS
SELECT * FROM TB_HEROIS WHERE NOME = 'Batman'

--UPDATE
UPDATE TB_HEROIS 
SET NOME = 'Osamu Dazai', PODER = 'Não Mais Humano'
WHERE ID = 2;

--DELETE
DELETE FROM TB_HEROIS WHERE ID = 3